image: python:3.12

stages:
  - lint
  - test

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .

flake8:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose

django:
  stage: test
  script:
    - pip install parameterized==0.9.0 -r requirements/prod.txt
    - cd herald
    - python3 manage.py test